services:
  dms_kiosk:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    command: "node server.js"
    environment:
      - PORT=4000
      - NODE_ENV=production

    env_file:
      - ../../.env
    ports:
      - "4000:4000"
